/**
 * C1 Advanced English Course - Data Part 3
 * Units 5-6: Sustainability & Innovation, Linguistic Diversity
 */

if (!window.courseData) window.courseData = { units: [] };

courseData.units.push(
    {
        id: 5,
        title: "Sustainability & Innovation",
        topic: "Green Technology & the Circular Economy",
        listening: {
            title: "Reimagining the Economy: From Linear to Circular",
            transcript: "For centuries, the global economy has operated on a fundamentally linear model: extract raw materials, manufacture products, consume them, and dispose of the waste. This take-make-waste paradigm has driven unprecedented economic growth, but at an increasingly unsustainable cost to the planet. The Earth's finite resources are being depleted at a rate that far outstrips their capacity for renewal. Landfills overflow, oceans choke with plastic debris, and the carbon emissions generated by manufacturing and transportation continue to accelerate climate change at an alarming velocity. In response to this existential crisis, a growing number of economists, engineers, and policymakers are championing an alternative approach: the circular economy. Inspired by the regenerative processes found in natural ecosystems, the circular economy model seeks to eliminate waste entirely by designing products for durability, reuse, remanufacturing, and recycling. Rather than extracting virgin materials, circular systems keep existing materials in use for as long as possible, extracting maximum value before returning them to the biosphere in a form that enriches rather than pollutes. Companies like Patagonia, which repairs and resells used garments, and Interface, which has pioneered the use of recycled fishing nets in carpet tiles, demonstrate that circular business models can be both environmentally responsible and commercially viable. However, transitioning to a circular economy at scale requires systemic changes that go far beyond individual corporate initiatives. It demands reimagined supply chains, supportive regulatory frameworks, and perhaps most critically, a fundamental shift in consumer behaviour away from disposability towards stewardship. The question is not whether we can afford to make this transition, but whether we can afford not to.",
            questions: [
                { q: "What model has the global economy traditionally followed?", options: ["Circular", "Linear", "Sustainable"], correct: 1 },
                { q: "What is the 'take-make-waste' paradigm?", options: ["A recycling process", "The linear economic model", "A manufacturing technique"], correct: 1 },
                { q: "What inspires the circular economy model?", options: ["Industrial processes", "Regenerative natural ecosystems", "Financial markets"], correct: 1 },
                { q: "What does the circular model seek to eliminate?", options: ["Jobs", "Waste entirely", "Trade"], correct: 1 },
                { q: "What does Patagonia do with used garments?", options: ["Burns them", "Repairs and resells them", "Exports them"], correct: 1 },
                { q: "What has Interface pioneered?", options: ["Electric cars", "Recycled fishing nets in carpet tiles", "Solar panels"], correct: 1 },
                { q: "What does transitioning to a circular economy require?", options: ["Only corporate initiatives", "Systemic changes", "Government subsidies alone"], correct: 1 },
                { q: "What must shift in consumer behaviour?", options: ["Buying more", "From disposability to stewardship", "Shopping online"], correct: 1 },
                { q: "What is accelerating climate change?", options: ["Circular models", "Carbon emissions from manufacturing", "Renewable energy"], correct: 1 },
                { q: "What is happening to landfills?", options: ["They are shrinking", "They overflow", "They are becoming parks"], correct: 1 }
            ]
        },
        reading: {
            title: "Carbon Capture and the Promise of Negative Emissions Technology",
            text: "Even the most optimistic scenarios for reducing greenhouse gas emissions acknowledge that decarbonisation alone will be insufficient to avert catastrophic climate change. The Intergovernmental Panel on Climate Change (IPCC) has concluded that virtually all pathways to limiting global warming to 1.5°C above pre-industrial levels require not just drastic emission reductions but also the active removal of carbon dioxide from the atmosphere—a capability known as negative emissions. This sobering assessment has spurred intense interest in carbon capture and storage (CCS) technologies, which aim to capture CO₂ at its source or directly from ambient air and sequester it permanently underground or in durable products.<br><br>Direct Air Capture (DAC) represents perhaps the most ambitious approach. Companies like Climeworks in Switzerland and Carbon Engineering in Canada have developed industrial-scale facilities that use chemical processes to extract CO₂ directly from the atmosphere. The captured carbon can then be compressed and injected into geological formations for permanent storage, converted into synthetic fuels, or mineralised into building materials. However, the technology faces formidable challenges. Current DAC systems are extraordinarily energy-intensive, requiring significant amounts of electricity to power the fans, heaters, and chemical reactions involved. To be genuinely carbon-negative, this energy must come from renewable or zero-carbon sources, creating a significant scaling constraint.<br><br>Nature-based solutions offer a complementary approach. Reforestation, afforestation, peatland restoration, and regenerative agriculture all enhance the biosphere's natural capacity to absorb and store carbon. These approaches offer co-benefits such as biodiversity conservation, soil health improvement, and community livelihood support. However, their permanence is uncertain—forests can burn, and agricultural practices can change. The most robust climate strategies will likely combine technological and nature-based approaches, recognising that no single solution is sufficient to address a challenge of this magnitude.<br><br>Critics caution that an overreliance on speculative negative emissions technologies could create a 'moral hazard,' giving governments and corporations an excuse to delay the difficult but necessary work of reducing emissions at source.",
            questions: [
                { q: "What has the IPCC concluded about limiting warming?", options: ["Only emission cuts are needed", "Active carbon removal is also required", "Technology cannot help"], correct: 1 },
                { q: "What does CCS stand for?", options: ["Climate Change Solutions", "Carbon Capture and Storage", "Carbon Counting System"], correct: 1 },
                { q: "What is Direct Air Capture (DAC)?", options: ["Filtering indoor air", "Extracting CO₂ from the atmosphere", "Measuring air quality"], correct: 1 },
                { q: "Which company developed DAC in Switzerland?", options: ["Climeworks", "Carbon Engineering", "Tesla"], correct: 0 },
                { q: "What can captured carbon be converted into?", options: ["Food products", "Synthetic fuels or building materials", "Medicines"], correct: 1 },
                { q: "What challenge does DAC face?", options: ["Lack of interest", "Extraordinary energy intensity", "Too much carbon captured"], correct: 1 },
                { q: "What are nature-based solutions?", options: ["Building nuclear plants", "Reforestation and regenerative agriculture", "Manufacturing solar panels"], correct: 1 },
                { q: "Why is the permanence of nature-based solutions uncertain?", options: ["Trees grow slowly", "Forests can burn", "Soil erodes"], correct: 1 },
                { q: "What is the 'moral hazard' concern?", options: ["Technology costing too much", "Excusing delay in reducing emissions", "Nature solutions failing"], correct: 1 },
                { q: "What will the most robust climate strategies combine?", options: ["Only DAC", "Technological and nature-based approaches", "Only regulations"], correct: 1 }
            ]
        },
        grammar: {
            title: "Participle Clauses",
            explanation: "Participle clauses use present participles (-ing), past participles (-ed/irregular), or perfect participles (having + past participle) to replace relative clauses or adverbial clauses, creating more concise sentences. They can express reason, result, time, or condition.",
            example: "Having invested heavily in renewables, the country reduced its carbon footprint. (= Because the country had invested...) / Built from recycled materials, the building won an architecture award. (= The building, which was built from...)",
            quizzes: [
                { question: "_____ completed the feasibility study, the engineers began construction.", options: ["Have", "Having", "Been"], correct: 1 },
                { question: "The report, _____ by an independent panel, raised serious concerns.", options: ["commissioning", "commissioned", "having commissioned"], correct: 1 },
                { question: "_____ from sustainable sources, the materials reduced environmental impact.", options: ["Sourcing", "Sourced", "Having sourcing"], correct: 1 },
                { question: "The scientist stood at the podium, _____ her groundbreaking findings.", options: ["presenting", "presented", "having presented"], correct: 0 },
                { question: "_____ worked in renewable energy for decades, she understood the challenges.", options: ["Have", "Having", "Being"], correct: 1 },
                { question: "The waste, _____ properly, can be converted into biofuel.", options: ["processing", "processed", "having process"], correct: 1 },
                { question: "_____ that the project was viable, investors committed funding.", options: ["Convinced", "Convincing", "Having convince"], correct: 0 },
                { question: "The company redesigned its packaging, _____ plastic use by 40%.", options: ["reduced", "reducing", "having reduce"], correct: 1 },
                { question: "_____ been exposed to harsh conditions, the solar panels required replacement.", options: ["Have", "Having", "Being"], correct: 1 },
                { question: "_____ across multiple industries, the circular economy model is gaining traction.", options: ["Adopted", "Adopting", "Having adopt"], correct: 0 }
            ]
        },
        vocabulary: [
            { word: "Sustainability", ipa: "səˌsteɪnəˈbɪləti", def: "Meeting present needs without compromising future generations' ability to meet theirs" },
            { word: "Decarbonisation", ipa: "diːˌkɑːbənaɪˈzeɪʃən", def: "The reduction or removal of carbon dioxide emissions" },
            { word: "Sequestration", ipa: "ˌsiːkwɪˈstreɪʃən", def: "The process of capturing and storing carbon dioxide" },
            { word: "Biodegradable", ipa: "ˌbaɪəʊdɪˈɡreɪdəbəl", def: "Capable of being decomposed by biological organisms" },
            { word: "Reforestation", ipa: "ˌriːfɒrɪˈsteɪʃən", def: "The process of replanting trees in a deforested area" },
            { word: "Stewardship", ipa: "ˈstjuːədʃɪp", def: "The responsible management and care of resources" },
            { word: "Infrastructure", ipa: "ˈɪnfrəstrʌktʃər", def: "The basic physical systems and structures needed for operation" },
            { word: "Renewable", ipa: "rɪˈnjuːəbəl", def: "Energy from sources that are naturally replenished" },
            { word: "Unprecedented", ipa: "ʌnˈpresɪdentɪd", def: "Never done or experienced before" },
            { word: "Viable", ipa: "ˈvaɪəbəl", def: "Capable of working successfully; feasible" }
        ],
        collocations: [
            { pair: ["Carbon", "footprint"], context: "We must reduce our _____ footprint to combat climate change.", distractors: ["pollution", "emission"] },
            { pair: ["Renewable", "energy"], context: "Investment in _____ energy sources is accelerating globally.", distractors: ["clean", "green"] },
            { pair: ["Circular", "economy"], context: "The _____ economy eliminates waste through design.", distractors: ["round", "closed"] },
            { pair: ["Supply", "chain"], context: "Disruptions in the global _____ chain affect production.", distractors: ["delivery", "trade"] },
            { pair: ["Greenhouse", "gas"], context: "_____ gas emissions are the primary driver of climate change.", distractors: ["Carbon", "Toxic"] },
            { pair: ["Fossil", "fuels"], context: "Phasing out _____ fuels is essential for decarbonisation.", distractors: ["old", "natural"] },
            { pair: ["Zero", "waste"], context: "The city adopted a _____-_____ policy for municipal operations.", distractors: ["no", "nil"] },
            { pair: ["Environmental", "impact"], context: "An _____ impact assessment must precede any construction.", distractors: ["ecological", "nature"] },
            { pair: ["Sustainable", "development"], context: "_____ development balances economic growth with environmental protection.", distractors: ["Green", "Eco"] },
            { pair: ["Climate", "crisis"], context: "The _____ crisis demands immediate and coordinated global action.", distractors: ["weather", "warming"] }
        ],
        pronunciation: {
            word_stress: [
                { word: "sus-tain-a-BIL-i-ty", syllables: ["sus", "tain", "a", "BIL", "i", "ty"], correct: 3 },
                { word: "de-car-bon-i-SA-tion", syllables: ["de", "car", "bon", "i", "SA", "tion"], correct: 4 },
                { word: "se-ques-TRA-tion", syllables: ["se", "ques", "TRA", "tion"], correct: 2 },
                { word: "bi-o-de-GRAD-a-ble", syllables: ["bi", "o", "de", "GRAD", "a", "ble"], correct: 3 },
                { word: "re-for-est-A-tion", syllables: ["re", "for", "est", "A", "tion"], correct: 3 },
                { word: "STEW-ard-ship", syllables: ["STEW", "ard", "ship"], correct: 0 },
                { word: "IN-fra-struc-ture", syllables: ["IN", "fra", "struc", "ture"], correct: 0 },
                { word: "re-NEW-a-ble", syllables: ["re", "NEW", "a", "ble"], correct: 1 },
                { word: "un-PREC-e-dent-ed", syllables: ["un", "PREC", "e", "dent", "ed"], correct: 1 },
                { word: "VI-a-ble", syllables: ["VI", "a", "ble"], correct: 0 }
            ],
            sentence_stress: [
                { sentence: "Having invested in renewables, the country reduced emissions.", stressed: ["invested", "renewables", "country", "reduced", "emissions"] },
                { sentence: "The circular economy eliminates waste through innovative design.", stressed: ["circular", "economy", "eliminates", "waste", "innovative", "design"] },
                { sentence: "Carbon capture technology faces significant scaling challenges.", stressed: ["Carbon", "capture", "technology", "faces", "significant", "scaling", "challenges"] },
                { sentence: "Sustainable development requires balancing economic and environmental goals.", stressed: ["Sustainable", "development", "requires", "balancing", "economic", "environmental", "goals"] },
                { sentence: "Built from recycled materials, the structure won an award.", stressed: ["Built", "recycled", "materials", "structure", "won", "award"] }
            ]
        },
        writing: "Write an argumentative essay evaluating whether carbon capture and storage technology is a genuine solution to climate change or a dangerous distraction from emission reduction. Use participle clauses to create sophisticated sentence structures. Discuss both technological and nature-based approaches, and consider the concept of 'moral hazard.' Aim for 300+ words.",
        speaking: "You are presenting at a sustainability conference. Make a case for why a specific industry (fashion, agriculture, technology, or construction) should transition to a circular economy model. Provide concrete examples of companies that have successfully adopted circular practices, and address the economic concerns of sceptics.",
        verb_patterns: {
            exercises: [
                { sentence: "The government committed _____ carbon emissions by 60% by 2040.", options: ["reducing", "to reducing", "to reduce"], correct: 1 },
                { sentence: "Environmentalists advocate _____ single-use plastics entirely.", options: ["to ban", "banning", "ban"], correct: 1 },
                { sentence: "The company pledged _____ carbon-neutral within five years.", options: ["becoming", "to become", "become"], correct: 1 },
                { sentence: "Consumers tend _____ the environmental cost of fast fashion.", options: ["to underestimate", "underestimating", "underestimate"], correct: 0 },
                { sentence: "Scientists warned against _____ on unproven technologies.", options: ["to rely", "relying", "rely"], correct: 1 },
                { sentence: "The initiative involves _____ local communities in conservation.", options: ["engaging", "to engage", "engage"], correct: 0 },
                { sentence: "The report urged governments _____ investment in green infrastructure.", options: ["to prioritise", "prioritising", "prioritise"], correct: 0 },
                { sentence: "They anticipate _____ the targets ahead of schedule.", options: ["to meet", "meeting", "meet"], correct: 1 },
                { sentence: "The factory managed _____ its waste output by 80%.", options: ["reducing", "to reduce", "reduce"], correct: 1 },
                { sentence: "Researchers hesitated _____ definitive conclusions from preliminary data.", options: ["to draw", "drawing", "draw"], correct: 0 }
            ]
        },
        functionalLanguage: {
            functionName: "Making Weekend Plans & Hype",
            description: "Learn how to suggest plans, agree to go out, express excitement, or decline social invitations in a natural, colloquial peer-to-peer way.",
            phrases: [
                { phrase: "I'm down for...", def: "a highly casual, common way to say you are willing, interested, or agreeing to do an activity", example: "If you guys are going to the new taco place tonight, I'm totally down for that!" },
                { phrase: "To have FOMO", def: "an acronym for 'Fear Of Missing Out'; the uneasy feeling that others are having fun while you are absent", example: "I stayed home to study on Saturday but had major FOMO looking at everyone's party photos." },
                { phrase: "Not really my cup of tea", def: "used to politely and casually say that something does not appeal to your personal taste or preferences", example: "Going to a loud, crowded nightclub is not really my cup of tea; I prefer a cozy pub." },
                { phrase: "To paint the town red", def: "to go out into a city or town and have a wild, highly active, and fun night out celebrating", example: "It's our last night of exams, so let's go out and absolutely paint the town red!" }
            ],
            task: "Your friends are planning a big night out celebrating a birthday, but you are exhausted. Write a casual text message (3 sentences) proposing a relaxed alternative or expressing your feelings, using at least two phrases above."
        },
        videos: [
            { title: "What Is the Circular Economy?", channel: "Ellen MacArthur Foundation", duration: "3:49", url: "https://www.youtube.com/watch?v=zCRKvDyyHmI" },
            { title: "Can We Fix Climate Change?", channel: "Kurzgesagt", duration: "16:22", url: "https://www.youtube.com/watch?v=LxgMdjyw8uw" },
            { title: "Direct Air Capture — Explained", channel: "Undecided with Matt Ferrell", duration: "15:47", url: "https://www.youtube.com/watch?v=XHX9pmQ6m_s" }
        ]
    },
    {
        id: 6,
        title: "Linguistic Diversity",
        topic: "Language, Identity & Endangered Languages",
        listening: {
            title: "The Silent Extinction: Losing the World's Languages",
            transcript: "Of the approximately seven thousand languages currently spoken across the globe, linguists estimate that nearly half are in danger of disappearing within the next century. This represents an extinction rate that dwarfs even the alarming loss of biological species, and its consequences for human knowledge, culture, and cognitive diversity are incalculable. Every fortnight, on average, the last fluent speaker of a language passes away, and with them vanishes an entire system of knowledge, a unique worldview encoded in grammar and vocabulary, and centuries of accumulated oral tradition. The reasons for language death are complex and multifaceted. Globalisation and the dominance of a handful of prestige languages—English, Mandarin, Spanish, Arabic—exert enormous pressure on smaller linguistic communities. Economic necessity compels speakers of minority languages to adopt the language of commerce and education, often at the expense of their mother tongue. In many cases, governmental policies of linguistic homogenisation, ranging from subtle institutional neglect to outright prohibition, have accelerated the process. The loss of a language is far more than the disappearance of a communication system. Languages encode unique knowledge about the natural world: indigenous languages in the Amazon contain detailed botanical vocabularies that have no equivalent in European languages. Languages embed philosophical and conceptual frameworks: the Hopi language, for instance, structures time fundamentally differently from Indo-European languages, offering insights into alternative ways of conceptualising reality. Efforts to reverse language death include documentation projects, immersion education programmes, and digital revitalisation initiatives that use technology to create learning resources for endangered languages. The success of the Hebrew and Welsh revival movements demonstrates that language revitalisation is possible, though it requires sustained commitment, resources, and community engagement.",
            questions: [
                { q: "How many languages are currently spoken worldwide?", options: ["About three thousand", "About seven thousand", "About ten thousand"], correct: 1 },
                { q: "How many languages may disappear within a century?", options: ["A quarter", "Nearly half", "All of them"], correct: 1 },
                { q: "How often does a language's last speaker pass away?", options: ["Every month", "Every fortnight", "Every year"], correct: 1 },
                { q: "What exerts pressure on smaller linguistic communities?", options: ["Local traditions", "Globalisation and prestige languages", "Scientific research"], correct: 1 },
                { q: "What do indigenous Amazonian languages contain?", options: ["No useful knowledge", "Detailed botanical vocabularies", "Only spoken traditions"], correct: 1 },
                { q: "How does Hopi structure time differently?", options: ["Using numbers", "Fundamentally differently from Indo-European languages", "Using seasons only"], correct: 1 },
                { q: "What are immersion education programmes?", options: ["Study abroad programmes", "Programmes teaching through endangered languages", "Online courses"], correct: 1 },
                { q: "Which language revivals are cited as successful?", options: ["Latin and Greek", "Hebrew and Welsh", "Sanskrit and Gaelic"], correct: 1 },
                { q: "What accelerates language death?", options: ["Language documentation", "Governmental policies of homogenisation", "Technology"], correct: 1 },
                { q: "What vanishes when a last speaker dies?", options: ["Just words", "An entire system of knowledge and worldview", "Only pronunciation"], correct: 1 }
            ]
        },
        reading: {
            title: "The Sapir-Whorf Hypothesis Revisited: Does Language Shape Thought?",
            text: "Few ideas in linguistics have generated as much fascination and controversy as the hypothesis that the language we speak fundamentally shapes the way we think and perceive the world. In its strongest form, known as linguistic determinism, this hypothesis posits that language determines thought—that the categories and structures available in our language constrain what we can conceive and express. The weaker version, linguistic relativity, suggests that while language does not determine thought absolutely, it influences habitual patterns of thinking and perception in measurable ways.<br><br>The hypothesis is named after the American linguists Edward Sapir and his student Benjamin Lee Whorf, who studied the languages of Native American peoples in the early twentieth century. Whorf's most famous claim concerned the Hopi language, which he argued lacked the grammatical markers of time found in European languages, leading its speakers to conceptualise time in fundamentally different ways. Although this specific claim has been largely discredited by subsequent research, the broader question of whether and how language influences cognition remains one of the most active areas of inquiry in contemporary linguistics and cognitive science.<br><br>Recent empirical research has lent considerable support to a nuanced version of the hypothesis. Studies by Lera Boroditsky and her colleagues have demonstrated that speakers of different languages systematically differ in how they think about time, space, colour, and causality. Speakers of Mandarin, for instance, tend to think about time vertically (months going up and down), whereas English speakers conceptualise time horizontally (past to the left, future to the right). The Kuuk Thaayorre people of Australia, whose language uses absolute cardinal directions rather than relative spatial terms, demonstrate remarkably precise spatial orientation that correlates with their linguistic framework.<br><br>These findings carry profound implications for our understanding of human cognition and cultural diversity. They suggest that linguistic diversity is not merely a matter of having different words for the same concepts, but rather that different languages literally partition and organise reality in distinct ways.",
            questions: [
                { q: "What is linguistic determinism?", options: ["Language is random", "Language determines thought", "Thought determines language"], correct: 1 },
                { q: "What is the weaker version called?", options: ["Linguistic relativism", "Linguistic relativity", "Linguistic universalism"], correct: 1 },
                { q: "Who is the hypothesis named after?", options: ["Chomsky and Pinker", "Sapir and Whorf", "Saussure and Jakobson"], correct: 1 },
                { q: "What language did Whorf study in depth?", options: ["Navajo", "Hopi", "Cherokee"], correct: 1 },
                { q: "Who has conducted modern research on the hypothesis?", options: ["Noam Chomsky", "Lera Boroditsky", "Steven Pinker"], correct: 1 },
                { q: "How do Mandarin speakers tend to think about time?", options: ["Horizontally", "Vertically", "Circularly"], correct: 1 },
                { q: "How do English speakers conceptualise time?", options: ["Vertically", "Horizontally", "Randomly"], correct: 1 },
                { q: "What do the Kuuk Thaayorre use instead of relative terms?", options: ["Gestures", "Absolute cardinal directions", "Sun position"], correct: 1 },
                { q: "What do the findings suggest about linguistic diversity?", options: ["It's superficial", "Languages partition reality differently", "All languages are the same"], correct: 1 },
                { q: "Has Whorf's specific Hopi claim been validated?", options: ["Yes, entirely", "Largely discredited", "Never tested"], correct: 1 }
            ]
        },
        grammar: {
            title: "The Subjunctive Mood",
            explanation: "The subjunctive mood is used in formal English to express wishes, demands, suggestions, and hypothetical situations. Key patterns include: 'It is essential/vital/imperative that + subject + base verb' (mandative subjunctive), 'If + subject + were' (hypothetical), and fixed expressions like 'as it were,' 'be that as it may,' 'come what may.'",
            example: "The committee insists that the report be submitted by Friday. / If linguistic diversity were to disappear, humanity would lose invaluable knowledge. / Be that as it may, the evidence remains inconclusive.",
            quizzes: [
                { question: "It is essential that the documentation _____ completed before the language disappears.", options: ["is", "be", "will be"], correct: 1 },
                { question: "The linguist insisted that every dialect _____ recorded.", options: ["was", "be", "is"], correct: 1 },
                { question: "If the language _____ to die out, centuries of knowledge would be lost.", options: ["was", "were", "is"], correct: 1 },
                { question: "The proposal recommends that funding _____ allocated immediately.", options: ["is", "be", "will be"], correct: 1 },
                { question: "It is imperative that the community _____ involved in revitalisation efforts.", options: ["is", "be", "was"], correct: 1 },
                { question: "_____ that as it may, the research findings are significant.", options: ["Be", "Being", "Is"], correct: 0 },
                { question: "She suggested that the student _____ the original text in the native language.", options: ["reads", "read", "reading"], correct: 1 },
                { question: "If every language _____ equally valued, fewer would face extinction.", options: ["was", "were", "is"], correct: 1 },
                { question: "The resolution demands that all member states _____ minority language rights.", options: ["protect", "protects", "protecting"], correct: 0 },
                { question: "It is vital that this knowledge _____ preserved for future generations.", options: ["is", "be", "will be"], correct: 1 }
            ]
        },
        vocabulary: [
            { word: "Linguistic", ipa: "lɪŋˈɡwɪstɪk", def: "Relating to language or the study of language" },
            { word: "Revitalisation", ipa: "ˌriːvaɪtəlaɪˈzeɪʃən", def: "The process of imbuing something with new life and vitality" },
            { word: "Paradigm", ipa: "ˈpærədaɪm", def: "A typical example, pattern, or model of something" },
            { word: "Cognate", ipa: "ˈkɒɡneɪt", def: "A word that has the same origin as another in a different language" },
            { word: "Vernacular", ipa: "vəˈnækjʊlər", def: "The everyday language spoken by ordinary people in a region" },
            { word: "Morphology", ipa: "mɔːˈfɒlədʒi", def: "The study of the forms and structure of words" },
            { word: "Bilingualism", ipa: "baɪˈlɪŋɡwəlɪzəm", def: "The ability to speak two languages fluently" },
            { word: "Etymology", ipa: "ˌetɪˈmɒlədʒi", def: "The study of the origin and history of words" },
            { word: "Pidgin", ipa: "ˈpɪdʒɪn", def: "A simplified language used between groups with no common tongue" },
            { word: "Assimilation", ipa: "əˌsɪmɪˈleɪʃən", def: "The process of absorbing into a larger cultural or linguistic group" }
        ],
        collocations: [
            { pair: ["Mother", "tongue"], context: "Her _____ tongue is Guaraní, but she also speaks Spanish.", distractors: ["first", "native"] },
            { pair: ["Dead", "language"], context: "Latin is often described as a _____ language.", distractors: ["old", "lost"] },
            { pair: ["Native", "speaker"], context: "A _____ speaker can provide authentic pronunciation models.", distractors: ["natural", "real"] },
            { pair: ["Lingua", "franca"], context: "English serves as a global _____ franca.", distractors: ["language", "speech"] },
            { pair: ["Language", "barrier"], context: "The _____ barrier prevented effective communication.", distractors: ["speech", "word"] },
            { pair: ["Oral", "tradition"], context: "Much indigenous knowledge is preserved through _____ tradition.", distractors: ["spoken", "verbal"] },
            { pair: ["Cultural", "heritage"], context: "Language is an integral part of _____ heritage.", distractors: ["national", "social"] },
            { pair: ["Language", "acquisition"], context: "Children go through stages of _____ acquisition.", distractors: ["speech", "word"] },
            { pair: ["Endangered", "species"], context: "Languages, like _____ species, face extinction threats.", distractors: ["threatened", "rare"] },
            { pair: ["Cognitive", "diversity"], context: "Linguistic diversity contributes to _____ diversity.", distractors: ["mental", "brain"] }
        ],
        pronunciation: {
            word_stress: [
                { word: "lin-GUIS-tic", syllables: ["lin", "GUIS", "tic"], correct: 1 },
                { word: "re-vi-tal-i-SA-tion", syllables: ["re", "vi", "tal", "i", "SA", "tion"], correct: 4 },
                { word: "PAR-a-digm", syllables: ["PAR", "a", "digm"], correct: 0 },
                { word: "COG-nate", syllables: ["COG", "nate"], correct: 0 },
                { word: "ver-NAC-u-lar", syllables: ["ver", "NAC", "u", "lar"], correct: 1 },
                { word: "mor-PHOL-o-gy", syllables: ["mor", "PHOL", "o", "gy"], correct: 1 },
                { word: "bi-LIN-gual-ism", syllables: ["bi", "LIN", "gual", "ism"], correct: 1 },
                { word: "e-ty-MOL-o-gy", syllables: ["e", "ty", "MOL", "o", "gy"], correct: 2 },
                { word: "PID-gin", syllables: ["PID", "gin"], correct: 0 },
                { word: "as-sim-i-LA-tion", syllables: ["as", "sim", "i", "LA", "tion"], correct: 3 }
            ],
            sentence_stress: [
                { sentence: "It is essential that endangered languages be documented.", stressed: ["essential", "endangered", "languages", "documented"] },
                { sentence: "Linguistic diversity reflects the richness of human cognition.", stressed: ["Linguistic", "diversity", "reflects", "richness", "human", "cognition"] },
                { sentence: "If every language were equally valued, fewer would face extinction.", stressed: ["every", "language", "equally", "valued", "fewer", "extinction"] },
                { sentence: "The Sapir-Whorf hypothesis suggests language influences thought.", stressed: ["Sapir-Whorf", "hypothesis", "suggests", "language", "influences", "thought"] },
                { sentence: "Oral traditions carry irreplaceable knowledge about the natural world.", stressed: ["Oral", "traditions", "carry", "irreplaceable", "knowledge", "natural", "world"] }
            ]
        },
        writing: "Write an essay arguing whether governments have a moral obligation to protect endangered languages. Use the subjunctive mood in formal recommendations. Discuss the Sapir-Whorf hypothesis and what is lost when a language dies—not just words, but worldviews and knowledge systems. Consider whether technology can play a meaningful role in language revitalisation. Aim for 300+ words.",
        speaking: "You are a sociolinguist presenting to a UNESCO committee. Make the case for or against the proposition that English as a global lingua franca is ultimately beneficial for humanity. Address the tension between the practical advantages of a common language and the cultural losses associated with linguistic homogenisation.",
        verb_patterns: {
            exercises: [
                { sentence: "The linguist recommended _____ immersion programmes in indigenous communities.", options: ["to establish", "establishing", "establish"], correct: 1 },
                { sentence: "UNESCO urged governments _____ funding for language documentation.", options: ["increasing", "to increase", "increase"], correct: 1 },
                { sentence: "The elders refused _____ their traditional language abandoned.", options: ["to let", "letting", "let"], correct: 0 },
                { sentence: "Children naturally acquire languages without _____ to study grammar rules.", options: ["to need", "needing", "need"], correct: 1 },
                { sentence: "Researchers intend _____ a comprehensive dictionary of the dying language.", options: ["compiling", "to compile", "compile"], correct: 1 },
                { sentence: "The community resented _____ forced to speak the national language.", options: ["to be", "being", "be"], correct: 1 },
                { sentence: "She devoted her career to _____ endangered languages.", options: ["document", "documenting", "to document"], correct: 1 },
                { sentence: "The school permitted students _____ in their mother tongue.", options: ["to communicate", "communicating", "communicate"], correct: 0 },
                { sentence: "He regretted not _____ his grandparents' language as a child.", options: ["to learn", "learning", "learn"], correct: 1 },
                { sentence: "Technology enables linguists _____ interactive learning resources.", options: ["creating", "to create", "create"], correct: 1 }
            ]
        },
        functionalLanguage: {
            functionName: "Being Hooked on Phones & Screen Time",
            description: "Master highly common colloquial expressions to talk about digital distraction, phone addiction, and setting boundaries with technology.",
            phrases: [
                { phrase: "To be glued to your screen", def: "unable to stop looking at your smartphone, laptop, or tablet screen for long periods of time", example: "We went out for dinner but he spent the whole evening completely glued to his screen!" },
                { phrase: "To phub someone", def: "a blend of 'phone' and 'snub'; to ignore the person you are with in social settings by looking at your phone instead", example: "It is incredibly frustrating when you are trying to tell a story and the other person just phubs you." },
                { phrase: "To go cold turkey", def: "to completely, suddenly, and immediately stop a habit or addiction instead of slowing down gradually", example: "I was spending four hours a day scrolling on TikTok, so I went cold turkey and deleted the app." },
                { phrase: "To unplug", def: "to temporarily disconnect from all digital devices, social media, and internet technology to rest and recharge", example: "I'm heading to a remote cabin this weekend to completely unplug and get some peace and quiet." }
            ],
            task: "You notice a friend is constantly phubbing you and always glued to their screen. Write a friendly, gentle intervention text (3 sentences) suggesting you both unplug, using at least two of the phrases."
        },
        videos: [
            { title: "Why Do Languages Die?", channel: "TED-Ed", duration: "4:53", url: "https://www.youtube.com/watch?v=Wp5FelcOPwU" },
            { title: "Does Language Shape the Way We Think?", channel: "Lera Boroditsky at TED", duration: "14:12", url: "https://www.youtube.com/watch?v=RKK7wGAYP6k" },
            { title: "The Last Speakers — Saving Dying Languages", channel: "National Geographic", duration: "5:36", url: "https://www.youtube.com/watch?v=rGuXY4B0pMA" }
        ]
    }
);
